# Generated by Django 3.2.18 on 2023-04-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('user_pass_word', models.CharField(blank=True, max_length=100, null=True)),
                ('user_created_on', models.DateTimeField(auto_now_add=True)),
                ('user_modified_on', models.DateTimeField(auto_now_add=True)),
                ('user_status', models.CharField(blank=True, max_length=10, null=True)),
                ('user_is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
