# Generated by Django 3.2.18 on 2023-04-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_action_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLedgerTransactionsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('seller_identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('total_product_price', models.FloatField(blank=True, null=True)),
                ('total_tax_applied', models.FloatField(blank=True, null=True)),
                ('total_price_with_tax', models.FloatField(blank=True, null=True)),
                ('bethel_commission', models.FloatField(blank=True, null=True)),
                ('tax_bethel_commission', models.FloatField(blank=True, null=True)),
                ('seller_price', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('seller_total_amount', models.FloatField(blank=True, null=True)),
                ('seller_has_GST', models.BooleanField()),
                ('GST_identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('seller_it_tds', models.FloatField(blank=True, null=True)),
                ('seller_gst_tds', models.FloatField(blank=True, null=True)),
                ('received_transaction_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('received_transaction_date', models.DateTimeField(auto_now_add=True)),
                ('seller_name', models.CharField(blank=True, max_length=150, null=True)),
                ('total_cess_applied', models.FloatField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField()),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': '"bethel"."z_brm_sales_ledger_txn"',
            },
        ),
    ]
