# Generated by Django 3.2.18 on 2023-05-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_action_manager', '0003_auto_20230425_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('user_email', models.CharField(blank=True, max_length=150, null=True)),
                ('user_pass_word', models.CharField(blank=True, max_length=100, null=True)),
                ('user_created_on', models.DateTimeField(auto_now_add=True)),
                ('user_modified_on', models.DateTimeField(auto_now_add=True)),
                ('user_login_status', models.BooleanField(default=True)),
                ('user_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
