# Generated by Django 3.2.18 on 2023-05-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_action_manager', '0004_auto_20230528_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGraphModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_column='User.first_name', max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, db_column='User.last_name', max_length=200, null=True)),
                ('gender', models.CharField(blank=True, db_column='User.gender', max_length=10, null=True)),
                ('nick_name', models.CharField(blank=True, db_column='User.nick_name', max_length=200, null=True)),
                ('user_id', models.IntegerField(db_column='User.id')),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_login_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LocationGraphModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, db_column='Location.name', max_length=200, null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Location.longitude', null=True)),
                ('latitude', models.FloatField(blank=True, db_column='Location.latitude', null=True)),
                ('discription', models.CharField(blank=True, db_column='Location.discription', max_length=20000, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='Location.user', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_action_manager.usergraphmodel')),
            ],
        ),
    ]
