# Generated by Django 3.2.18 on 2023-06-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_action_manager', '0005_auto_20230529_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_uid',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.DeleteModel(
            name='LocationGraphModel',
        ),
        migrations.DeleteModel(
            name='UserGraphModel',
        ),
    ]
