# Generated by Django 3.2.18 on 2023-06-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_action_manager', '0006_auto_20230605_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_pass_word',
            new_name='user_password',
        ),
    ]
