# Generated by Django 3.2.18 on 2023-06-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_action_manager', '0009_alter_usermodel_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_login_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_modified_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
